FROM node:18 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npx nx build api

FROM node:18

WORKDIR /app

COPY --from=build /app/dist/projects/api .

RUN npm install --omit=dev

EXPOSE 3333

CMD ["node", "main.js"]
