FROM node:22 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npx nx build api

FROM node:22

WORKDIR /app

COPY --from=build /app/dist/projects/api .

RUN npm install

EXPOSE 3333

CMD ["node", "main.js"]
